spring:
  jpa:
    hibernate:
      ddl-auto: ${ddl-auto:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        # 格式化输出sql
        format_sql: true
    show-sql: true
   # flyway设置
  flyway:
    enabled: false
    baseline-on-migrate: false
    baseline-version: 0
  datasource:
    url: jdbc:mysql://${db.host:127.0.0.1}:${db.port:3306}/${db.name:work_home}?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${db.username:root}
    password: ${db.password:}
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
server:
  # 配置端口
  port: ${port:8002}
